name : Rahul CI self hosted



on: 
  push:
    branches: ["main", "master"]
  pull_request: 
    branches: ["main", "master"]

  workflow_dispatch:

jobs:

  first_job:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v3

      - name: Run a single line script
        run: echo Hello duniya

      - name: Run a poly-line script
        run: |
          echo This is first line and,
  
  second_job:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Add other actions to Test on build,
          echo Deploy successfull.